properties:
  irq-gpios:
    $ref: /include/dt-bindings/gpio/gpio.yaml#/definitions/gpio-controller
  cs-gpios:
    $ref: /include/dt-bindings/gpio/gpio.yaml#/definitions/gpio-controller

  # ここから追記 ↓↓
  automouse-layer:
    type: int
    required: false
    description: "Trackball 操作中に自動的にアクティブにするレイヤー番号"

  scroll-layers:
    type: int
    required: false
    description: "スクロールモード時に切り替えるレイヤー一覧"

  snipe-layers:
    type: int
    required: false
    description: "スナイプ（精密移動）モード時に切り替えるレイヤー一覧"
