manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: mygithub
      url-base: https://github.com/maru-x
    - name: mctechnology17
      url-base: https://github.com/mctechnology17
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: pat912x-driver
      remote: mygithub # 自分の GitHub またはローカルパス
      revision: main
      path: modules/zephyr/pat912x
    - name: zmk-pmw3360-driver
      remote: mygithub
      revision: main
      path: modules/zephyr/pmw3360
    - name: zmk-nice-oled
      remote: mctechnology17
      revision: main
  self:
    path: config
