manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: mygithub
      url-base: https://github.com/maru-x
    - name: mctechnology17
      url-base: https://github.com/mctechnology17
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: pat912x-driver
      remote: mygithub # 自分の GitHub またはローカルパス
      revision: main
      path: modules/zephyr/pat912x
    #    - name: zmk-pmw3360-driver
    #      remote: mygithub
    #      revision: main
    #      path: modules/zephyr/pmw3360
    - name: zmk-nice-oled
      remote: mctechnology17
      revision: main
    - name: zmk-mouse-click-back
      remote: mygithub # 自分の GitHub またはローカルパス
      path: modules/zephyr/click_back
      revision: main
    - name: zmk-trans-to
      remote: mygithub # 自分の GitHub またはローカルパス
      path: modules/zephyr/trans_to
      revision: main
  self:
    path: config
