manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
   - name: trentrand
     url-base: https://github.com/trentrand
    - name: mctechnology17
      url-base: https://github.com/mctechnology17
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
   - name: zmk-pmw3360-driver
     remote: trentrand
     revision: main
    - name: zmk-nice-oled
      remote: mctechnology17
      revision: main
  self:
    path: config
